modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="modeldumper"
version="1.0.0"
displayName="Model Dumper"
description='''Automatically exports all entity, item, and armor models with textures for use in thumbnail creation.'''
authors="ModelDumper Team"

[[dependencies.modeldumper]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.modeldumper]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"
